jobs:
  codecov:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11, 19
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'maven-

          '
    - continue-on-error: true
      run: mvn install -Pjacoco
    - continue-on-error: true
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
name: codecov
on:
  repository_dispatch:
    types: trigger-ga___codecov.yml
