jobs:
  mvn:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-jdk-${{ matrix.java }}-maven-

          '
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: mvn -version
    - continue-on-error: true
      run: mvn --errors --batch-mode clean install -Pqulice
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 19
        os:
        - ubuntu-22.04
        - windows-2022
        - macos-12
name: mvn
on:
  repository_dispatch:
    types: trigger-ga___mvn.yml
