jobs:
  pdd:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: volodya-lombrozo/pdd-action@master
name: pdd
on:
  repository_dispatch:
    types: trigger-ga___pdd.yml
