jobs:
  xcop:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: g4s8/xcop-action@master
name: xcop
on:
  repository_dispatch:
    types: trigger-ga___xcop.yml
